DROP TABLE PATIENTSTATES IF EXISTS;
DROP TABLE EXPERTS IF EXISTS;

CREATE TABLE PATIENTSTATES (
  EVENTID VARCHAR(25) PRIMARY KEY,
  CASESTATE VARCHAR(25),
  PATIENTID VARCHAR(25),
  HEALTHSTATE  VARCHAR(20),
  EMOTIONALSTATE  VARCHAR(20),
  PATIENTPOSITION VARCHAR(20),
  PATIENTLOCATION VARCHAR(20),
  AUDIOSEQUENZE VARCHAR(50),
  VIDEOSEQUENZE VARCHAR(50)
);

CREATE TABLE EXPERTS (
  EXPERTID VARCHAR(25) PRIMARY KEY,
  CONTACTINORMATION VARCHAR(100),
  MEDICALFIELD VARCHAR(75),
  FIELDOFEXPERTISE  VARCHAR(75),
  ISGP  VARCHAR(10),
  ISALERTCHAIN VARCHAR(10),
  ISCOLLABORATION VARCHAR(10),
  ISANNOTATION VARCHAR(10)
);
